//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazilimMuhProje.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yorumlar()
        {
            this.YorumAnaliz = new HashSet<YorumAnaliz>();
        }
    
        public int YorumId { get; set; }
        public int KullaniciId { get; set; }
        public string YorumMetni { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public int ResimId { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Resimler Resimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YorumAnaliz> YorumAnaliz { get; set; }
    }
}
