//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazilimMuhProje.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class YorumAnaliz
    {
        public int AnalizId { get; set; }
        public int YorumId { get; set; }
        public string DuyguDurumu { get; set; }
    
        public virtual Yorumlar Yorumlar { get; set; }
    }
}
